"""init

Revision ID: 25473f68de7b
Revises: 
Create Date: 2015-07-25 09:49:19.319746

"""

# revision identifiers, used by Alembic.
revision = '25473f68de7b'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('begin', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('result_type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_card', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('rarity', sa.Text(), nullable=True),
    sa.Column('id_contest', sa.Integer(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('idolized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votesession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('contest', sa.Integer(), nullable=True),
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.Column('left_rarity', sa.Text(), nullable=True),
    sa.Column('right_rarity', sa.Text(), nullable=True),
    sa.Column('left_name', sa.Text(), nullable=True),
    sa.Column('right_name', sa.Text(), nullable=True),
    sa.Column('left_idolized', sa.Boolean(), nullable=True),
    sa.Column('right_idolized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votesession')
    op.drop_table('votes')
    op.drop_table('contest')
    ### end Alembic commands ###
